"""remove-metadata-unique-constraint

Revision ID: 08fc1814ab22
Revises: b0a72718582d
Create Date: 2021-07-14 18:36:11.912891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08fc1814ab22'
down_revision = 'b0a72718582d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifact_metadata', schema=None) as batch_op:
        batch_op.drop_constraint('uq_artifact_metadata_name_artifact_id_value_type', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifact_metadata', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_artifact_metadata_name_artifact_id_value_type', ['name', 'artifact_id', 'value', 'type'])
    # ### end Alembic commands ###
