"""exported_objects

Revision ID: 6856092ff104
Revises: e08b8c343fa6
Create Date: 2020-12-04 15:41:05.905716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6856092ff104'
down_revision = 'e08b8c343fa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exported_objects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(length=256), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('exporter_id', sa.Integer(), nullable=False),
    sa.Column('external_object_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exporter_id'], ['exporters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_id', 'object_type', 'exporter_id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_artifacts_exporter_id_exporters', type_='foreignkey')
        batch_op.drop_column('exporter_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exporter_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_artifacts_exporter_id_exporters', 'exporters', ['exporter_id'], ['id'])

    op.drop_table('exported_objects')
    # ### end Alembic commands ###
