"""fix-tag-constraint

Revision ID: 9a1314b315e7
Revises: 08fc1814ab22
Create Date: 2021-07-14 18:49:47.297641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a1314b315e7'
down_revision = '08fc1814ab22'
branch_labels = None
depends_on = None


def upgrade():
    convention = {
        "uq": "uq__%(table_name)s__%(column_0_name)s__%(column_1_name)s",
    }
    op.execute("update artifact_tags set source='' where source is NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifact_tags', schema=None,
                              naming_convention=convention) as batch_op:
        #batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint("uq__artifact_tags__tag__artifact_id")
        batch_op.alter_column('source',
            existing_type=sa.VARCHAR(length=256),
            nullable=False)
        batch_op.create_unique_constraint(
            "uq_artifact_tag_tag_artifact_id_source",
            ['tag', 'artifact_id', 'source'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifact_tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('source',
            existing_type=sa.VARCHAR(length=256),
            nullable=True)
    # ### end Alembic commands ###
