"""candidate-artifacts

Revision ID: b0a72718582d
Revises: f799323c9ee8
Create Date: 2021-07-12 04:42:58.363315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0a72718582d'
down_revision = 'f799323c9ee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('mtime', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('dataset', 'executable', 'methodology', 'metrics', 'priorwork', 'publication', 'hypothesis', 'code', 'domain', 'supportinginfo', name='candidate_artifact_enum'), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('imported_artifact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['imported_artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_artifact_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_artifact_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=16384), nullable=False),
    sa.Column('type', sa.String(length=256), nullable=True),
    sa.Column('source', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['candidate_artifact_id'], ['candidate_artifacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'candidate_artifact_id', 'value', 'type')
    )
    op.create_table('candidate_artifact_relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=True),
    sa.Column('relation', sa.Enum('cites', 'supplements', 'continues', 'references', 'documents', 'compiles', 'publishes', 'indexes', 'extends', 'uses', name='candidate_artifact_relationship_enum'), nullable=True),
    sa.Column('related_candidate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['related_candidate_id'], ['candidate_artifacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id', 'relation', 'related_candidate_id')
    )
    op.create_table('candidate_relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_artifact_id', sa.Integer(), nullable=True),
    sa.Column('relation', sa.Enum('cites', 'supplements', 'continues', 'references', 'documents', 'compiles', 'publishes', 'indexes', 'extends', 'uses', name='candidate_relationship_enum'), nullable=True),
    sa.Column('related_candidate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_artifact_id'], ['candidate_artifacts.id'], ),
    sa.ForeignKeyConstraint(['related_candidate_id'], ['candidate_artifacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_artifact_id', 'relation', 'related_candidate_id')
    )
    with op.batch_alter_table("artifact_relationships",recreate="always") as batch_op:
        batch_op.alter_column(
            "relation",
            type_=sa.Enum(
                "cites","supplements","continues","references","documents",
                "compiles","publishes","indexes","extends","uses"),
            existing_type=sa.Enum(
                "cites","supplements","continues","references","documents",
                "compiles","publishes"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_relationships')
    op.drop_table('candidate_artifact_relationships')
    op.drop_table('candidate_artifact_metadata')
    op.drop_table('candidate_artifacts')
    with op.batch_alter_table("artifact_relationships",recreate="always") as batch_op:
        batch_op.alter_column(
            "relation",
            type_=sa.Enum(
                "cites","supplements","continues","references","documents",
                "compiles","publishes"),
            existing_type=sa.Enum(
                "cites","supplements","continues","references","documents",
                "compiles","publishes","indexes","extends","uses"))
    # ### end Alembic commands ###
